[2024-06-09T12:30:50.633+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T12:30:50.646+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: My_first_dag.extract_real_time manual__2024-06-09T10:30:18+00:00 [queued]>
[2024-06-09T12:30:50.649+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: My_first_dag.extract_real_time manual__2024-06-09T10:30:18+00:00 [queued]>
[2024-06-09T12:30:50.649+0200] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-06-09T12:30:50.654+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_real_time> on 2024-06-09 10:30:18+00:00
[2024-06-09T12:30:50.663+0200] {standard_task_runner.py:63} INFO - Started process 81280 to run task
[2024-06-09T12:30:50.667+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'My_first_dag', 'extract_real_time', 'manual__2024-06-09T10:30:18+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/my_datalake.py', '--cfg-path', '/var/folders/lz/gv7z_f1x3156jvrgkgylt68w0000gn/T/tmphiy5dybf']
[2024-06-09T12:30:50.670+0200] {standard_task_runner.py:91} INFO - Job 70: Subtask extract_real_time
[2024-06-09T12:30:50.691+0200] {task_command.py:426} INFO - Running <TaskInstance: My_first_dag.extract_real_time manual__2024-06-09T10:30:18+00:00 [running]> on host macbook-air-de-noe.local
[2024-06-09T12:30:50.718+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='My_first_dag' AIRFLOW_CTX_TASK_ID='extract_real_time' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T10:30:18+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T10:30:18+00:00'
[2024-06-09T12:30:50.719+0200] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T12:30:51.879+0200] {logging_mixin.py:188} INFO - API data fetched successfully from Belib' - Disponibilité Temps Réel!
[2024-06-09T12:30:51.915+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T12:30:51.916+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/noejalabert/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noejalabert/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noejalabert/airflow_venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noejalabert/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noejalabert/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noejalabert/airflow/dags/lib/extract_belib_real_time.py", line 48, in extract_real_time
    save_data_to_file(data)
  File "/Users/noejalabert/airflow/dags/lib/extract_belib_real_time.py", line 37, in save_data_to_file
    os.makedirs(destination_path, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/Users/dags'
[2024-06-09T12:30:51.923+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=My_first_dag, task_id=extract_real_time, execution_date=20240609T103018, start_date=20240609T103050, end_date=20240609T103051
[2024-06-09T12:30:51.930+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task extract_real_time ([Errno 13] Permission denied: '/Users/dags'; 81280)
[2024-06-09T12:30:51.942+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T12:30:51.957+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T12:30:51.959+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
